# -*- coding: utf-8 -*-
# Deployment settings for fifteen.
# This file is autogenerated by the mkb system and used by the s3e deployment
# tool during the build process.

config = {}
cmdline = ['C:/Marmalade/6.1/s3e/makefile_builder/mkb.py', 'c:/Users/Vano468/Documents/Marmalade Projects/Fifteen/fifteen.mkb', '--deploy-only']
mkb = 'c:/Users/Vano468/Documents/Marmalade Projects/Fifteen/fifteen.mkb'
mkf = ['c:\\marmalade\\6.1\\modules\\iwgx\\iwgx.mkf', 'c:\\marmalade\\6.1\\modules\\iwgeom\\iwgeom.mkf', 'c:\\marmalade\\6.1\\modules\\iwutil\\iwutil.mkf', u'c:\\users\\vano468\\appdata\\roaming\\marmalade\\packages\\6.1.1\\libjpeg_6b\\libjpeg.mkf', u'c:\\users\\vano468\\appdata\\roaming\\marmalade\\packages\\6.1.1\\libpng_1.2.34\\libpng.mkf', u'c:\\users\\vano468\\appdata\\roaming\\marmalade\\packages\\6.1.1\\zlib_1.2.4\\zlib.mkf', 'c:\\marmalade\\6.1\\modules\\iwresmanager\\iwresmanager.mkf', 'c:\\marmalade\\6.1\\modules\\iwgl\\iwgl.mkf']

class DeployConfig(object):
    pass

######### ASSET GROUPS #############

assets = {}

assets['Default'] = [
    ('c:/Users/Vano468/Documents/Marmalade Projects/Fifteen\data', '.', 0),
]

######### DEFAULT CONFIG #############

class DefaultConfig(DeployConfig):
    embed_icf = -1
    name = 'fifteen'
    pub_sign_key = 0
    priv_sign_key = 0
    caption = 'fifteen'
    long_caption = 'fifteen'
    version = [0, 0, 1]
    config = ['c:/Users/Vano468/Documents/Marmalade Projects/Fifteen/data/app.icf']
    data_dir = 'c:/Users/Vano468/Documents/Marmalade Projects/Fifteen/data'
    iphone_link_lib = []
    linux_ext_lib = []
    iphone_link_libdir = []
    iphone_link_opts = []
    osx_ext_dll = []
    android_external_jars = []
    android_external_res = []
    android_supports_gl_texture = []
    android_extra_manifest = []
    iphone_link_libdirs = []
    android_extra_application_manifest = []
    win32_ext_dll = []
    android_so = []
    iphone_link_libs = []
    target = {
         'arm' : {
                   'debug'   : r'c:/Users/Vano468/Documents/Marmalade Projects/Fifteen/build_fifteen_vc10/Debug_fifteen_VC10_arm/fifteen.s3e',
                   'release' : r'c:/Users/Vano468/Documents/Marmalade Projects/Fifteen/build_fifteen_vc10/Release_fifteen_VC10_arm/fifteen.s3e',
                 },
         'mips_gcc' : {
                   'debug'   : r'c:/Users/Vano468/Documents/Marmalade Projects/Fifteen/build_fifteen_vc10/Debug_fifteen_VC10_gcc_mips/fifteen.so',
                   'release' : r'c:/Users/Vano468/Documents/Marmalade Projects/Fifteen/build_fifteen_vc10/Release_fifteen_VC10_gcc_mips/fifteen.so',
                 },
         'x86' : {
                   'debug'   : r'c:/Users/Vano468/Documents/Marmalade Projects/Fifteen/build_fifteen_vc10/Debug_fifteen_VC10_x86/fifteen.s86',
                   'release' : r'c:/Users/Vano468/Documents/Marmalade Projects/Fifteen/build_fifteen_vc10/Release_fifteen_VC10_x86/fifteen.s86',
                 },
         'arm_gcc' : {
                   'debug'   : r'c:/Users/Vano468/Documents/Marmalade Projects/Fifteen/build_fifteen_vc10/Debug_fifteen_VC10_gcc_arm/fifteen.s3e',
                   'release' : r'c:/Users/Vano468/Documents/Marmalade Projects/Fifteen/build_fifteen_vc10/Release_fifteen_VC10_gcc_arm/fifteen.s3e',
                 },
        }
    assets = assets['Default']

default = DefaultConfig()
